# Phase-1

# Data Collection/preparation part.

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

**Between 2001 and 2012, India consisted ofÂ 28 States and 7 Union Territories.**

In [2]:
#list of STATES and UTs
STATE_UT = ['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA',
            'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA PRADESH', 'MAHARASHTRA',
            'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU',
            'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI',
            'DAMAN & DIU', 'DELHI', 'LAKSHADWEEP', 'PUDUCHERRY']

# 1. Collection of the population data for each state and union territory from the years 2001 to 2012.

**The population census, which is conducted every 10 years, provides data for the years 2001 and 2011. This means we only have information on the population for these two specific years.**

**Population data source link-wikipedia**

https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population.

State/UT           Population (2001)    Population (2011)

Andhra Pradesh        75,728,400           84,664,012            
Arunachal Pradesh     1,098,328            1,383,727
Assam                 26,638,600           31,169,272
Bihar                 82,879,910           103,804,630
Chhattisgarh          20,834,530           25,540,196
Goa                   1,348,900            1,457,723
Gujarat               50,597,200           60,383,628
Haryana               21,083,900           25,753,081
Himachal Pradesh      6,077,453            6,856,509
Jammu & Kashmir       10,070,300           12,548,926
Jharkhand             26,946,070           32,988,134
Karnataka             52,734,986           61,130,704
Kerala                31,839,000           33,387,677
Madhya Pradesh        60,385,090           72,597,565
Maharashtra           96,752,500           112,372,972
Manipur               2,294,480            2,721,756
Meghalaya             2,306,540            2,964,007
Mizoram               889,690              1,091,014
Nagaland              1,990,275            1,980,602
Odisha                36,707,900           41,947,358
Punjab                24,289,130           27,704,236
Rajasthan             56,473,300           68,621,012
Sikkim                541,902              607,688
Tamil Nadu            62,111,390           72,138,958
Tripura               3,191,880            3,671,032
Uttar Pradesh         166,053,600          199,581,477
Uttarakhand           8,489,100            10,116,752
West Bengal           80,221,300           91,347,736
A & N Islands         356,650              379,944
Chandigarh            901,080              1,054,686
D & N Haveli          220,963              342,853
Daman & Diu           158,080              242,911
Delhi                 13,851,503           16,753,235
Lakshadweep           61,300               64,429
Puducherry            974,820              1,244,464

In [3]:
# List containing the population data for each state and UT in year 2001
population_2001 = [75728400, 1098328, 26638600, 82879910, 20834530, 1348900, 50597200, 21083900, 6077453, 10070300, 26946070, 
                   52734986, 31839000, 60385090, 96752500, 2294480, 2306540, 889690, 1990275, 36707900, 24289130, 56473300, 
                   541902, 62111390, 3191880, 166053600, 8489100, 80221300, 356650, 901080, 220963, 158080, 13851503, 61300, 
                   974820]

In [4]:
# List containing the population data for each state and UT in year 2011
population_2011 = [84664012, 1383727, 31169272, 103804630, 25540196, 1457723, 60383628, 25753081, 6856509, 12548926, 32988134, 
                   61130704, 33387677, 72597565, 112372972, 2721756, 2964007, 1091014, 1980602, 41947358, 27704236, 68621012, 
                   607688, 72138958, 3671032, 199581477, 10116752, 91347736, 379944, 1054686, 342853, 242911, 16753235, 64429, 
                   1244464]

# 2. Collection of the literacy rate data for each state and union territory from the years 2001 to 2012.

**Literacy rate data source link-wikipedia**

https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate

State/UT        Literacy Rate (%) - 2001   Literacy Rate (%) - 2011

Andhra Pradesh        60.47                      67.02
Arunachal Pradesh     54.34                      65.38
Assam                 63.25                      72.19
Bihar                 47.00                      61.80
Chhattisgarh          64.66                      70.28
Goa                   82.01                      88.70
Gujarat               69.14                      78.03
Haryana               67.91                      75.55
Himachal Pradesh      76.48                      82.80
Jammu & Kashmir       55.52                      67.16
Jharkhand             53.56                      66.41
Karnataka             66.06                      75.36
Kerala                90.86                      94.00
Madhya Pradesh        63.74                      69.32
Maharashtra           76.84                      82.34
Manipur               70.50                      76.94
Meghalaya             62.56                      74.43
Mizoram               88.80                      91.33
Nagaland              66.59                      79.55
Odisha                63.08                      72.87
Punjab                69.65                      75.84
Rajasthan             60.41                      66.11
Sikkim                68.81                      81.42
Tamil Nadu            73.45                      80.33
Tripura               73.19                      87.22
Uttar Pradesh         56.27                      67.68
Uttarakhand           71.62                      78.82
West Bengal           68.64                      76.26
A & N Islands         81.30                      86.63
Chandigarh            81.94                      86.05
D & N Haveli          57.63                      76.24
Daman & Diu           78.18                      87.10
Delhi                 81.67                      86.21
Lakshadweep           86.66                      91.85
Puducherry            81.24                      85.85

In [5]:
# List containing the literacy rate data for each state and UT in year 2001
literacy_rate_2001 = [60.47, 54.34, 63.25, 47.00, 64.66, 82.01, 69.14, 67.91, 76.48,55.52, 53.56, 66.06, 90.86, 63.74, 76.84, 
                      70.50, 62.56, 88.80, 66.59, 63.08, 69.65, 60.41, 68.81, 73.45, 73.19, 56.27, 71.62, 68.64, 81.3 , 81.94, 
                      57.63, 78.18, 81.67, 86.66, 81.24]

In [6]:
# List containing the literacy rate data for each state and UT in year 2011
literacy_rate_2011 = [67.02, 65.38, 72.19, 61.80, 70.28, 88.70, 78.03, 75.55, 82.80, 67.16, 66.41, 75.36, 94.00, 69.32, 82.34, 
                      76.94, 74.43, 91.33, 79.55, 72.87, 75.84, 66.11, 81.42, 80.33, 87.22, 67.68, 78.82, 76.26, 86.63, 86.05, 
                      76.24, 87.10, 86.21, 91.85, 85.85]

# 3. Collection of the area data for each state and union territory.

**Area data source link-wikipedia**

https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area

State/UT          Total Area (sq. km.)

Andhra Pradesh        275,045
Arunachal Pradesh     83,743
Assam                 78,438
Bihar                 94,163
Chhattisgarh          135,192
Goa                   3,702
Gujarat               196,244
Haryana               44,212
Himachal Pradesh      55,673
Jammu & Kashmir       222,236
Jharkhand             79,716
Karnataka             191,791
Kerala                38,852
Madhya Pradesh        308,252
Maharashtra           307,713
Manipur               22,327
Meghalaya             22,429
Mizoram               21,081
Nagaland              16,579
Odisha                155,707
Punjab                50,362
Rajasthan             342,239
Sikkim                7,096
Tamil Nadu            130,060
Tripura               10,486
Uttar Pradesh         240,928
Uttarakhand           53,483
West Bengal           88,752
A & N Islands         8,249
Chandigarh            114
D & N Haveli          491
Daman & Diu           111
Delhi                 1,483
Lakshadweep           30
Puducherry            490

In [7]:
# List containing the data of area of each state and UT
area_sq_km = [275045,  83743,  78438,  94163, 135192,   3702, 196244,  44212, 55673, 222236,  79716, 191791,  38852, 308252, 
              307713,  22327, 22429,  21081,  16579, 155707,  50362, 342239, 7096, 130060, 10486, 240928,  53483,  88752, 8249,    114,    491,    111,
              1483, 30, 490]

In [8]:
# Storing the collected into the dataframe
df = pd.DataFrame({'STATE/UT': STATE_UT, 
                   'AREA (sq. km.)': area_sq_km, 
                   'POPULATION (2001)': population_2001, 
                   'POPULATION (2011)': population_2011,
                   'LITERACY RATE (%) - 2001': literacy_rate_2001,
                   'LITERACY RATE (%) - 2011': literacy_rate_2011})

In [9]:
df

,STATE/UT,AREA (sq. km.),POPULATION (2001),POPULATION (2011),LITERACY RATE (%) - 2001,LITERACY RATE (%) - 2011
0,ANDHRA PRADESH,275045,75728400,84664012,60.47,67.02
1,ARUNACHAL PRADESH,83743,1098328,1383727,54.34,65.38
2,ASSAM,78438,26638600,31169272,63.25,72.19
3,BIHAR,94163,82879910,103804630,47.00,61.80
4,CHHATTISGARH,135192,20834530,25540196,64.66,70.28
5,GOA,3702,1348900,1457723,82.01,88.70
6,GUJARAT,196244,50597200,60383628,69.14,78.03
7,HARYANA,44212,21083900,25753081,67.91,75.55
8,HIMACHAL PRADESH,55673,6077453,6856509,76.48,82.80
9,JAMMU & KASHMIR,222236,10070300,12548926,55.52,67.16
10,JHARKHAND,79716,26946070,32988134,53.56,66.41
11,KARNATAKA,191791,52734986,61130704,66.06,75.36
12,KERALA,38852,31839000,33387677,90.86,94.00
13,MADHYA PRADESH,308252,60385090,72597565,63.74,69.32
14,MAHARASHTRA,307713,96752500,112372972,76.84,82.34
15,MANIPUR,22327,2294480,2721756,70.50,76.94
16,MEGHALAYA,22429,2306540,2964007,62.56,74.43
17,MIZORAM,21081,889690,1091014,88.80,91.33
18,NAGALAND,16579,1990275,1980602,66.59,79.55
19,ODISHA,155707,36707900,41947358,63.08,72.87
20,PUNJAB,50362,24289130,27704236,69.65,75.84
21,RAJASTHAN,342239,56473300,68621012,60.41,66.11
22,SIKKIM,7096,541902,607688,68.81,81.42
23,TAMIL NADU,130060,62111390,72138958,73.45,80.33
24,TRIPURA,10486,3191880,3671032,73.19,87.22
25,UTTAR PRADESH,240928,166053600,199581477,56.27,67.68
26,UTTARAKHAND,53483,8489100,10116752,71.62,78.82
27,WEST BENGAL,88752,80221300,91347736,68.64,76.26
28,A & N ISLANDS,8249,356650,379944,81.30,86.63
29,CHANDIGARH,114,901080,1054686,81.94,86.05
30,D & N HAVELI,491,220963,342853,57.63,76.24
31,DAMAN & DIU,111,158080,242911,78.18,87.10
32,DELHI,1483,13851503,16753235,81.67,86.21
33,LAKSHADWEEP,30,61300,64429,86.66,91.85
34,PUDUCHERRY,490,974820,1244464,81.24,85.85

# 4.collecting more information that will be useful for analysis later on.

**The dataset comprises population and literacy rate data only for the years 2001 and 2011. However, employing the linear interpolation method allows for the derivation of population and literacy rate data for all the remaining years.**

In [10]:
# Finding population for all other years with the help of linear interpolation

# Linear interpolation
start_year = 2001
end_year = 2011

# Calculate the annual change in population
df['Annual Change'] = (df['POPULATION (2011)'] - df['POPULATION (2001)']) / (end_year - start_year)

# Estimate population for intermediate years
intermediate_years = range(2002, 2013)
for year in intermediate_years:
    column_name = f'POPULATION ({year})'
    df[column_name] = (df['POPULATION (2001)'] + df['Annual Change'] * (year - start_year)).round()

# Drop the 'Annual Change' column
df.drop(columns = ['Annual Change'], axis = 1, inplace = True)

In [11]:
# Finding literacy rate for all other years with the help of linear interpolation

# Linear interpolation
start_year = 2001
end_year = 2011

# Calculate the annual change in literacy rate
df['Annual Change'] = (df['LITERACY RATE (%) - 2011'] - df['LITERACY RATE (%) - 2001']) / (end_year - start_year)

# Estimate literacy rates for intermediate years
intermediate_years = range(2002, 2013)
for year in intermediate_years:
    column_name = f'LITERACY RATE (%) - {year}'
    df[column_name] = (df['LITERACY RATE (%) - 2001'] + df['Annual Change'] * (year - start_year)).round(2)

# Drop the 'Annual Change' column
df.drop(columns = ['Annual Change'], axis = 1, inplace = True)

In [12]:
# Calculating the average population for each state and UT from 2001 to 2012
df['AVERAGE POPULATION (2001-2012)'] = df[['POPULATION (2001)', 'POPULATION (2002)', 'POPULATION (2003)', 'POPULATION (2004)',
                                           'POPULATION (2005)', 'POPULATION (2006)', 'POPULATION (2007)', 'POPULATION (2008)',
                                           'POPULATION (2009)', 'POPULATION (2010)', 'POPULATION (2011)', 'POPULATION (2012)'
                                            ]].mean(axis = 1).round()

In [13]:
# Calculating the average literacy rate for each state and UT from 2001 to 2012
df['AVERAGE LITERACY RATE (2001-2012)'] = df[['LITERACY RATE (%) - 2001', 'LITERACY RATE (%) - 2002', 'LITERACY RATE (%) - 2003', 
                                                  'LITERACY RATE (%) - 2004', 'LITERACY RATE (%) - 2005', 'LITERACY RATE (%) - 2006', 
                                                  'LITERACY RATE (%) - 2007', 'LITERACY RATE (%) - 2008', 'LITERACY RATE (%) - 2009', 
                                                  'LITERACY RATE (%) - 2010', 'LITERACY RATE (%) - 2011', 'LITERACY RATE (%) - 2012'
                                                  ]].mean(axis = 1).round(2)

In [14]:
# Calculating the population growth rate for each state and UT from 2001 to 2012
df['POPULATION GROWTH RATE (2001-2012)'] = (((df['POPULATION (2012)'] - df['POPULATION (2001)']) / df['POPULATION (2001)']) * 100).round()

In [15]:
df

,STATE/UT,AREA (sq. km.),POPULATION (2001),POPULATION (2011),LITERACY RATE (%) - 2001,LITERACY RATE (%) - 2011,POPULATION (2002),POPULATION (2003),POPULATION (2004),POPULATION (2005),...,LITERACY RATE (%) - 2005,LITERACY RATE (%) - 2006,LITERACY RATE (%) - 2007,LITERACY RATE (%) - 2008,LITERACY RATE (%) - 2009,LITERACY RATE (%) - 2010,LITERACY RATE (%) - 2012,AVERAGE POPULATION (2001-2012),AVERAGE LITERACY RATE (2001-2012),POPULATION GROWTH RATE (2001-2012)
0,ANDHRA PRADESH,275045,75728400,84664012.0,60.47,67.02,76621961.0,77515522.0,78409084.0,79302645.0,...,63.09,63.74,64.40,65.05,65.71,66.36,67.68,80642987.0,64.07,13.0
1,ARUNACHAL PRADESH,83743,1098328,1383727.0,54.34,65.38,1126868.0,1155408.0,1183948.0,1212488.0,...,58.76,59.86,60.96,62.07,63.17,64.28,66.48,1255298.0,60.41,29.0
2,ASSAM,78438,26638600,31169272.0,63.25,72.19,27091667.0,27544734.0,27997802.0,28450869.0,...,66.83,67.72,68.61,69.51,70.40,71.30,73.08,29130470.0,68.17,19.0
3,BIHAR,94163,82879910,103804630.0,47.00,61.80,84972382.0,87064854.0,89157326.0,91249798.0,...,52.92,54.40,55.88,57.36,58.84,60.32,63.28,94388506.0,55.14,28.0
4,CHHATTISGARH,135192,20834530,25540196.0,64.66,70.28,21305097.0,21775663.0,22246230.0,22716796.0,...,66.91,67.47,68.03,68.59,69.16,69.72,70.84,23422646.0,67.75,25.0
5,GOA,3702,1348900,1457723.0,82.01,88.70,1359782.0,1370665.0,1381547.0,1392429.0,...,84.69,85.36,86.02,86.69,87.36,88.03,89.37,1408753.0,85.69,9.0
6,GUJARAT,196244,50597200,60383628.0,69.14,78.03,51575843.0,52554486.0,53533128.0,54511771.0,...,72.70,73.59,74.47,75.36,76.25,77.14,78.92,55979735.0,74.03,21.0
7,HARYANA,44212,21083900,25753081.0,67.91,75.55,21550818.0,22017736.0,22484654.0,22951572.0,...,70.97,71.73,72.49,73.26,74.02,74.79,76.31,23651950.0,72.11,24.0
8,HIMACHAL PRADESH,55673,6077453,6856509.0,76.48,82.80,6155359.0,6233264.0,6311170.0,6389075.0,...,79.01,79.64,80.27,80.90,81.54,82.17,83.43,6505934.0,79.96,14.0
9,JAMMU & KASHMIR,222236,10070300,12548926.0,55.52,67.16,10318163.0,10566025.0,10813888.0,11061750.0,...,60.18,61.34,62.50,63.67,64.83,66.00,68.32,11433544.0,61.92,27.0
10,JHARKHAND,79716,26946070,32988134.0,53.56,66.41,27550276.0,28154483.0,28758689.0,29362896.0,...,58.70,59.98,61.27,62.56,63.84,65.12,67.69,30269205.0,60.63,25.0
11,KARNATAKA,191791,52734986,61130704.0,66.06,75.36,53574558.0,54414130.0,55253701.0,56093273.0,...,69.78,70.71,71.64,72.57,73.50,74.43,76.29,57352631.0,71.18,18.0
12,KERALA,38852,31839000,33387677.0,90.86,94.00,31993868.0,32148735.0,32303603.0,32458471.0,...,92.12,92.43,92.74,93.06,93.37,93.69,94.31,32690772.0,92.59,5.0
13,MADHYA PRADESH,308252,60385090,72597565.0,63.74,69.32,61606338.0,62827585.0,64048832.0,65270080.0,...,65.97,66.53,67.09,67.65,68.20,68.76,69.88,67101951.0,66.81,22.0
14,MAHARASHTRA,307713,96752500,112372972.0,76.84,82.34,98314547.0,99876594.0,101438642.0,103000689.0,...,79.04,79.59,80.14,80.69,81.24,81.79,82.89,105343760.0,79.87,18.0
15,MANIPUR,22327,2294480,2721756.0,70.50,76.94,2337208.0,2379935.0,2422663.0,2465390.0,...,73.08,73.72,74.36,75.01,75.65,76.30,77.58,2529482.0,74.04,20.0
16,MEGHALAYA,22429,2306540,2964007.0,62.56,74.43,2372287.0,2438033.0,2503780.0,2569527.0,...,67.31,68.50,69.68,70.87,72.06,73.24,75.62,2668147.0,69.09,31.0
17,MIZORAM,21081,889690,1091014.0,88.80,91.33,909822.0,929955.0,950087.0,970220.0,...,89.81,90.06,90.32,90.57,90.82,91.08,91.58,1000418.0,90.19,25.0
18,NAGALAND,16579,1990275,1980602.0,66.59,79.55,1989308.0,1988340.0,1987373.0,1986406.0,...,71.77,73.07,74.37,75.66,76.96,78.25,80.85,1984955.0,73.72,-1.0
19,ODISHA,155707,36707900,41947358.0,63.08,72.87,37231846.0,37755792.0,38279737.0,38803683.0,...,67.00,67.97,68.95,69.93,70.91,71.89,73.85,39589602.0,68.46,16.0
20,PUNJAB,50362,24289130,27704236.0,69.65,75.84,24630641.0,24972151.0,25313662.0,25655172.0,...,72.13,72.74,73.36,73.98,74.60,75.22,76.46,26167438.0,73.05,15.0
21,RAJASTHAN,342239,56473300,68621012.0,60.41,66.11,57688071.0,58902842.0,60117614.0,61332385.0,...,62.69,63.26,63.83,64.40,64.97,65.54,66.68,63154542.0,63.54,24.0
22,SIKKIM,7096,541902,607688.0,68.81,81.42,548481.0,555059.0,561638.0,568216.0,...,73.85,75.12,76.38,77.64,78.90,80.16,82.68,578084.0,75.75,13.0
23,TAMIL NADU,130060,62111390,72138958.0,73.45,80.33,63114147.0,64116904.0,65119660.0,66122417.0,...,76.20,76.89,77.58,78.27,78.95,79.64,81.02,67626552.0,77.23,18.0
24,TRIPURA,10486,3191880,3671032.0,73.19,87.22,3239795.0,3287710.0,3335626.0,3383541.0,...,78.80,80.20,81.61,83.01,84.41,85.82,88.62,3455414.0,80.91,17.0
25,UTTAR PRADESH,240928,166053600,199581477.0,56.27,67.68,169406388.0,172759175.0,176111963.0,179464751.0,...,60.83,61.98,63.12,64.26,65.40,66.54,68.82,184493932.0,62.55,22.0
26,UTTARAKHAND,53483,8489100,10116752.0,71.62,78.82,8651865.0,8814630.0,8977396.0,9140161.0,...,74.50,75.22,75.94,76.66,77.38,78.10,79.54,9384309.0,75.58,21.0
27,WEST BENGAL,88752,80221300,91347736.0,68.64,76.26,81333944.0,82446587.0,83559231.0,84671874.0,...,71.69,72.45,73.21,73.97,74.74,75.50,77.02,86340840.0,72.83,15.0
28,A & N ISLANDS,8249,356650,379944.0,81.30,86.63,358979.0,361309.0,363638.0,365968.0,...,83.43,83.96,84.50,85.03,85.56,86.10,87.16,369462.0,84.23,7.0
29,CHANDIGARH,114,901080,1054686.0,81.94,86.05,916441.0,931801.0,947162.0,962522.0,...,83.58,84.00,84.41,84.82,85.23,85.64,86.46,985563.0,84.20,19.0
30,D & N HAVELI,491,220963,342853.0,57.63,76.24,233152.0,245341.0,257530.0,269719.0,...,65.07,66.94,68.80,70.66,72.52,74.38,78.10,288002.0,67.87,61.0
31,DAMAN & DIU,111,158080,242911.0,78.18,87.10,166563.0,175046.0,183529.0,192012.0,...,81.75,82.64,83.53,84.42,85.32,86.21,87.99,204737.0,83.09,59.0
32,DELHI,1483,13851503,16753235.0,81.67,86.21,14141676.0,14431849.0,14722023.0,15012196.0,...,83.49,83.94,84.39,84.85,85.30,85.76,86.66,15447456.0,84.17,23.0
33,LAKSHADWEEP,30,61300,64429.0,86.66,91.85,61613.0,61926.0,62239.0,62552.0,...,88.74,89.26,89.77,90.29,90.81,91.33,92.37,63021.0,89.51,6.0
34,PUDUCHERRY,490,974820,1244464.0,81.24,85.85,1001784.0,1028749.0,1055713.0,1082678.0,...,83.08,83.54,84.01,84.47,84.93,85.39,86.31,1123124.0,83.78,30.0

In [16]:
df.to_csv('STATE_UT_POPULATION.csv', index = False)